/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLoteriasRouteImport } from './routes/_authenticated/loterias'
import { Route as AuthenticatedLLoteriaRouteRouteImport } from './routes/_authenticated/l/$loteria/route'
import { Route as AuthenticatedLLoteriaIndexRouteImport } from './routes/_authenticated/l/$loteria/index'
import { Route as AuthenticatedLLoteriaResultadosRouteImport } from './routes/_authenticated/l/$loteria/resultados'
import { Route as AuthenticatedLLoteriaJogosRouteImport } from './routes/_authenticated/l/$loteria/jogos'
import { Route as AuthenticatedLLoteriaHistoricoRouteImport } from './routes/_authenticated/l/$loteria/historico'
import { Route as AuthenticatedLLoteriaGeradorRouteImport } from './routes/_authenticated/l/$loteria/gerador'
import { Route as AuthenticatedLLoteriaDashboardRouteImport } from './routes/_authenticated/l/$loteria/dashboard'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLoteriasRoute = AuthenticatedLoteriasRouteImport.update({
  id: '/loterias',
  path: '/loterias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLLoteriaRouteRoute =
  AuthenticatedLLoteriaRouteRouteImport.update({
    id: '/l/$loteria',
    path: '/l/$loteria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLLoteriaIndexRoute =
  AuthenticatedLLoteriaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLLoteriaRouteRoute,
  } as any)
const AuthenticatedLLoteriaResultadosRoute =
  AuthenticatedLLoteriaResultadosRouteImport.update({
    id: '/resultados',
    path: '/resultados',
    getParentRoute: () => AuthenticatedLLoteriaRouteRoute,
  } as any)
const AuthenticatedLLoteriaJogosRoute =
  AuthenticatedLLoteriaJogosRouteImport.update({
    id: '/jogos',
    path: '/jogos',
    getParentRoute: () => AuthenticatedLLoteriaRouteRoute,
  } as any)
const AuthenticatedLLoteriaHistoricoRoute =
  AuthenticatedLLoteriaHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedLLoteriaRouteRoute,
  } as any)
const AuthenticatedLLoteriaGeradorRoute =
  AuthenticatedLLoteriaGeradorRouteImport.update({
    id: '/gerador',
    path: '/gerador',
    getParentRoute: () => AuthenticatedLLoteriaRouteRoute,
  } as any)
const AuthenticatedLLoteriaDashboardRoute =
  AuthenticatedLLoteriaDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedLLoteriaRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/resultados': typeof ResultadosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/loterias': typeof AuthenticatedLoteriasRoute
  '/l/$loteria': typeof AuthenticatedLLoteriaRouteRouteWithChildren
  '/l/$loteria/dashboard': typeof AuthenticatedLLoteriaDashboardRoute
  '/l/$loteria/gerador': typeof AuthenticatedLLoteriaGeradorRoute
  '/l/$loteria/historico': typeof AuthenticatedLLoteriaHistoricoRoute
  '/l/$loteria/jogos': typeof AuthenticatedLLoteriaJogosRoute
  '/l/$loteria/resultados': typeof AuthenticatedLLoteriaResultadosRoute
  '/l/$loteria/': typeof AuthenticatedLLoteriaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/resultados': typeof ResultadosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/loterias': typeof AuthenticatedLoteriasRoute
  '/l/$loteria/dashboard': typeof AuthenticatedLLoteriaDashboardRoute
  '/l/$loteria/gerador': typeof AuthenticatedLLoteriaGeradorRoute
  '/l/$loteria/historico': typeof AuthenticatedLLoteriaHistoricoRoute
  '/l/$loteria/jogos': typeof AuthenticatedLLoteriaJogosRoute
  '/l/$loteria/resultados': typeof AuthenticatedLLoteriaResultadosRoute
  '/l/$loteria': typeof AuthenticatedLLoteriaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/resultados': typeof ResultadosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/loterias': typeof AuthenticatedLoteriasRoute
  '/_authenticated/l/$loteria': typeof AuthenticatedLLoteriaRouteRouteWithChildren
  '/_authenticated/l/$loteria/dashboard': typeof AuthenticatedLLoteriaDashboardRoute
  '/_authenticated/l/$loteria/gerador': typeof AuthenticatedLLoteriaGeradorRoute
  '/_authenticated/l/$loteria/historico': typeof AuthenticatedLLoteriaHistoricoRoute
  '/_authenticated/l/$loteria/jogos': typeof AuthenticatedLLoteriaJogosRoute
  '/_authenticated/l/$loteria/resultados': typeof AuthenticatedLLoteriaResultadosRoute
  '/_authenticated/l/$loteria/': typeof AuthenticatedLLoteriaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/resultados'
    | '/sitemap.xml'
    | '/loterias'
    | '/l/$loteria'
    | '/l/$loteria/dashboard'
    | '/l/$loteria/gerador'
    | '/l/$loteria/historico'
    | '/l/$loteria/jogos'
    | '/l/$loteria/resultados'
    | '/l/$loteria/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/resultados'
    | '/sitemap.xml'
    | '/loterias'
    | '/l/$loteria/dashboard'
    | '/l/$loteria/gerador'
    | '/l/$loteria/historico'
    | '/l/$loteria/jogos'
    | '/l/$loteria/resultados'
    | '/l/$loteria'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/dashboard'
    | '/resultados'
    | '/sitemap.xml'
    | '/_authenticated/loterias'
    | '/_authenticated/l/$loteria'
    | '/_authenticated/l/$loteria/dashboard'
    | '/_authenticated/l/$loteria/gerador'
    | '/_authenticated/l/$loteria/historico'
    | '/_authenticated/l/$loteria/jogos'
    | '/_authenticated/l/$loteria/resultados'
    | '/_authenticated/l/$loteria/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ResultadosRoute: typeof ResultadosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/loterias': {
      id: '/_authenticated/loterias'
      path: '/loterias'
      fullPath: '/loterias'
      preLoaderRoute: typeof AuthenticatedLoteriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/l/$loteria': {
      id: '/_authenticated/l/$loteria'
      path: '/l/$loteria'
      fullPath: '/l/$loteria'
      preLoaderRoute: typeof AuthenticatedLLoteriaRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/l/$loteria/': {
      id: '/_authenticated/l/$loteria/'
      path: '/'
      fullPath: '/l/$loteria/'
      preLoaderRoute: typeof AuthenticatedLLoteriaIndexRouteImport
      parentRoute: typeof AuthenticatedLLoteriaRouteRoute
    }
    '/_authenticated/l/$loteria/resultados': {
      id: '/_authenticated/l/$loteria/resultados'
      path: '/resultados'
      fullPath: '/l/$loteria/resultados'
      preLoaderRoute: typeof AuthenticatedLLoteriaResultadosRouteImport
      parentRoute: typeof AuthenticatedLLoteriaRouteRoute
    }
    '/_authenticated/l/$loteria/jogos': {
      id: '/_authenticated/l/$loteria/jogos'
      path: '/jogos'
      fullPath: '/l/$loteria/jogos'
      preLoaderRoute: typeof AuthenticatedLLoteriaJogosRouteImport
      parentRoute: typeof AuthenticatedLLoteriaRouteRoute
    }
    '/_authenticated/l/$loteria/historico': {
      id: '/_authenticated/l/$loteria/historico'
      path: '/historico'
      fullPath: '/l/$loteria/historico'
      preLoaderRoute: typeof AuthenticatedLLoteriaHistoricoRouteImport
      parentRoute: typeof AuthenticatedLLoteriaRouteRoute
    }
    '/_authenticated/l/$loteria/gerador': {
      id: '/_authenticated/l/$loteria/gerador'
      path: '/gerador'
      fullPath: '/l/$loteria/gerador'
      preLoaderRoute: typeof AuthenticatedLLoteriaGeradorRouteImport
      parentRoute: typeof AuthenticatedLLoteriaRouteRoute
    }
    '/_authenticated/l/$loteria/dashboard': {
      id: '/_authenticated/l/$loteria/dashboard'
      path: '/dashboard'
      fullPath: '/l/$loteria/dashboard'
      preLoaderRoute: typeof AuthenticatedLLoteriaDashboardRouteImport
      parentRoute: typeof AuthenticatedLLoteriaRouteRoute
    }
  }
}

interface AuthenticatedLLoteriaRouteRouteChildren {
  AuthenticatedLLoteriaDashboardRoute: typeof AuthenticatedLLoteriaDashboardRoute
  AuthenticatedLLoteriaGeradorRoute: typeof AuthenticatedLLoteriaGeradorRoute
  AuthenticatedLLoteriaHistoricoRoute: typeof AuthenticatedLLoteriaHistoricoRoute
  AuthenticatedLLoteriaJogosRoute: typeof AuthenticatedLLoteriaJogosRoute
  AuthenticatedLLoteriaResultadosRoute: typeof AuthenticatedLLoteriaResultadosRoute
  AuthenticatedLLoteriaIndexRoute: typeof AuthenticatedLLoteriaIndexRoute
}

const AuthenticatedLLoteriaRouteRouteChildren: AuthenticatedLLoteriaRouteRouteChildren =
  {
    AuthenticatedLLoteriaDashboardRoute: AuthenticatedLLoteriaDashboardRoute,
    AuthenticatedLLoteriaGeradorRoute: AuthenticatedLLoteriaGeradorRoute,
    AuthenticatedLLoteriaHistoricoRoute: AuthenticatedLLoteriaHistoricoRoute,
    AuthenticatedLLoteriaJogosRoute: AuthenticatedLLoteriaJogosRoute,
    AuthenticatedLLoteriaResultadosRoute: AuthenticatedLLoteriaResultadosRoute,
    AuthenticatedLLoteriaIndexRoute: AuthenticatedLLoteriaIndexRoute,
  }

const AuthenticatedLLoteriaRouteRouteWithChildren =
  AuthenticatedLLoteriaRouteRoute._addFileChildren(
    AuthenticatedLLoteriaRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLoteriasRoute: typeof AuthenticatedLoteriasRoute
  AuthenticatedLLoteriaRouteRoute: typeof AuthenticatedLLoteriaRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLoteriasRoute: AuthenticatedLoteriasRoute,
  AuthenticatedLLoteriaRouteRoute: AuthenticatedLLoteriaRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ResultadosRoute: ResultadosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
